# Generated by Django 4.0.3 on 2022-04-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='number',
            field=models.CharField(blank=True, choices=[('plate recognition', 'plate extraction'), ('text_extraction', 'text extraction')], default='plate recognition', max_length=50, null=True),
        ),
    ]
