# Generated by Django 4.0.3 on 2022-04-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_plate_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plate',
            old_name='number',
            new_name='purpose',
        ),
    ]
