# Generated by Django 4.0.4 on 2022-04-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_owner_vehical_fine_complain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='district',
        ),
    ]
