# Generated by Django 4.0.4 on 2022-04-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_fine_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='reason',
            field=models.CharField(default='parking duty', max_length=800),
        ),
    ]
